// <auto-generated>
//   This code was generated by the Hexarc Pact tool. Do not edit.
//   Created: 2021-02-20 17:43:31Z
// </auto-generated>

#nullable enable

namespace Hexarc.Pact.Demo.Api.Models
{
    public enum Direction
    {
        Up = 0,
        Down = 1,
        Left = 2,
        Right = 3
    }
}

#nullable restore