// <auto-generated>
//   This code was generated by the Hexarc Pact tool. Do not edit.
// </auto-generated>

#nullable enable

namespace Hexarc.Pact.Demo.Api.Models
{
    public enum Flags
    {
        On = 1,
        Off = 2
    }
}

#nullable restore