// <auto-generated>
//   This code was generated by the Hexarc Pact tool. Do not edit.
//   Created: 2021-02-25 06:50:27Z
// </auto-generated>

#nullable enable

namespace Hexarc.Pact.Demo.Api.Models
{
    public enum Flags
    {
        On = 1,
        Off = 2
    }
}

#nullable restore