// <auto-generated>
//   This code was generated by the Hexarc Pact tool. Do not edit.
//   Created: 2021-02-20 17:43:31Z
// </auto-generated>

#nullable enable

namespace Hexarc.Pact.Demo.Api.Models
{
    public sealed class GeometryCollection
    {
        public System.Collections.Generic.List<Point> Points { get; set; }
        public System.Collections.Generic.List<Hexarc.Pact.Demo.Api.ModelsV2.Point> PointsV2 { get; set; }
        public System.Collections.Generic.Dictionary<System.Guid, Point> PointsDict { get; set; }
        public Direction Direction { get; set; }
    }
}

#nullable restore