// <auto-generated>
//   This code was generated by the Hexarc Pact tool. Do not edit.
//   Created: 2021-02-26 21:52:36Z
// </auto-generated>

#nullable enable

namespace Hexarc.Pact.Demo.Api.Models
{
    public sealed class Info<T1, T2>
    {
        public System.Collections.Generic.List<T1?> Items { get; set; } = default!;
        public System.Collections.Generic.Dictionary<System.String, T2?> Marks { get; set; } = default!;
    }
}

#nullable restore