// <auto-generated>
//   This code was generated by the Hexarc Pact tool. Do not edit.
//   Created: 2021-02-20 17:43:31Z
// </auto-generated>

#nullable enable

namespace Hexarc.Pact.Demo.Api.Models
{
    public sealed class Point
    {
        public System.Double X { get; set; }
        public System.Double Y { get; set; }
    }
}

namespace Hexarc.Pact.Demo.Api.ModelsV2
{
    public sealed class Point
    {
        public System.Double X { get; set; }
        public System.Double Y { get; set; }
    }
}

#nullable restore