// <auto-generated>
//   This code was generated by the Hexarc Pact tool. Do not edit.
//   Created: 2021-02-20 17:43:31Z
// </auto-generated>

#nullable enable

namespace Hexarc.Pact.Demo.Api.Models
{
    public sealed class Triangle
    {
        public Point V1 { get; set; }
        public Point V2 { get; set; }
        public Point V3 { get; set; }
    }
}

#nullable restore