// <auto-generated>
//   This code was generated by the Hexarc Pact tool. Do not edit.
// </auto-generated>

#nullable enable

namespace Hexarc.Pact.Demo.Api.Models
{
    public sealed class Triangle
    {
        public Point Vertex1 { get; set; } = default!;
        public Point Vertex2 { get; set; } = default!;
        public Point Vertex3 { get; set; } = default!;
    }
}

#nullable restore