// <auto-generated>
//   This code was generated by the Hexarc Pact tool. Do not edit.
//   Created: 2021-02-25 06:50:27Z
// </auto-generated>

#nullable enable

namespace Hexarc.Pact.Demo.Api.Models
{
    public sealed class Triangle
    {
        public Point V1 { get; set; } = default!;
        public Point V2 { get; set; } = default!;
        public Point V3 { get; set; } = default!;
    }
}

#nullable restore