// <auto-generated>
//   This code was generated by the Hexarc Pact tool. Do not edit.
//   Created: 2021-02-20 17:43:31Z
// </auto-generated>

#nullable enable

namespace Hexarc.Pact.Demo.Api.Controllers
{
    public sealed partial class AnimalController : Hexarc.Pact.Client.ControllerBase
    {
        public AnimalController(Hexarc.Pact.Client.ClientBase client, System.String controllerPath = "/Animals") : base(client, controllerPath)
        {
        }

        public async System.Threading.Tasks.Task<Hexarc.Pact.Demo.Api.Models.Animal?> GetAnimal()
        {
            return await this.GetJson<Hexarc.Pact.Demo.Api.Models.Animal?>("/GetAnimal", System.Array.Empty<Hexarc.Pact.Client.GetMethodParameter>());
        }
    }
}

#nullable restore