// <auto-generated>
//   This code was generated by the Hexarc Pact tool. Do not edit.
//   Created: 2021-02-20 19:32:46Z
// </auto-generated>

#nullable enable

namespace Hexarc.Pact.Demo.Api.Controllers
{
    public sealed partial class GeometryController : Hexarc.Pact.Client.ControllerBase
    {
        public GeometryController(Hexarc.Pact.Client.ClientBase client, System.String controllerPath = "/Geometry") : base(client, controllerPath)
        {
        }

        public async System.Threading.Tasks.Task<System.Double> Area(Hexarc.Pact.Demo.Api.Models.Triangle triangle)
        {
            return await this.PostJson<Hexarc.Pact.Demo.Api.Models.Triangle, System.Double>("/Area", triangle);
        }

        public async System.Threading.Tasks.Task<Hexarc.Pact.Demo.Api.Models.GeometryCollection?> ComputeCollection()
        {
            return await this.GetJson<Hexarc.Pact.Demo.Api.Models.GeometryCollection?>("/ComputeCollection", System.Array.Empty<Hexarc.Pact.Client.GetMethodParameter>());
        }
    }
}

#nullable restore