// <auto-generated>
//   This code was generated by the Hexarc Pact tool. Do not edit.
// </auto-generated>

#nullable enable

namespace Hexarc.Pact.Demo.Api.Controllers
{
    public sealed partial class MiscController : Hexarc.Pact.Client.ControllerBase
    {
        public MiscController(Hexarc.Pact.Client.ClientBase client, System.String controllerPath = "/Misc") : base(client, controllerPath)
        {
        }

        public async System.Threading.Tasks.Task<System.String> Ping(System.String message, System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.String>>? headers = default)
        {
            return await this.GetJson<System.String>("/Ping", new[] { new Hexarc.Pact.Client.GetMethodParameter(nameof(message), message) }, headers);
        }

        public async System.Threading.Tasks.Task<System.Int32> Sum(System.Int32 a, System.Int32 b, System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.String>>? headers = default)
        {
            return await this.GetJson<System.Int32>("/Sum", new[] { new Hexarc.Pact.Client.GetMethodParameter(nameof(a), a), new Hexarc.Pact.Client.GetMethodParameter(nameof(b), b) }, headers);
        }

        public async System.Threading.Tasks.Task<System.Double> Random(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.String>>? headers = default)
        {
            return await this.GetJson<System.Double>("/Random", System.Array.Empty<Hexarc.Pact.Client.GetMethodParameter>(), headers);
        }
    }
}

#nullable restore