// <auto-generated>
//   This code was generated by the Hexarc Pact tool. Do not edit.
// </auto-generated>

#nullable enable

namespace Hexarc.Pact.Demo.Api.Controllers
{
    public sealed partial class PrimitivesController : Hexarc.Pact.Client.ControllerBase
    {
        public PrimitivesController(Hexarc.Pact.Client.ClientBase client, System.String controllerPath = "/Primitives") : base(client, controllerPath)
        {
        }

        public async System.Threading.Tasks.Task<System.Boolean> GetBoolean(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.String>>? headers = default)
        {
            return await this.GetJson<System.Boolean>("/GetBoolean", System.Array.Empty<Hexarc.Pact.Client.GetMethodParameter>(), headers);
        }

        public async System.Threading.Tasks.Task<System.Byte> GetByte(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.String>>? headers = default)
        {
            return await this.GetJson<System.Byte>("/GetByte", System.Array.Empty<Hexarc.Pact.Client.GetMethodParameter>(), headers);
        }

        public async System.Threading.Tasks.Task<System.SByte> GetSByte(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.String>>? headers = default)
        {
            return await this.GetJson<System.SByte>("/GetSByte", System.Array.Empty<Hexarc.Pact.Client.GetMethodParameter>(), headers);
        }

        public async System.Threading.Tasks.Task<System.Char> GetChar(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.String>>? headers = default)
        {
            return await this.GetJson<System.Char>("/GetChar", System.Array.Empty<Hexarc.Pact.Client.GetMethodParameter>(), headers);
        }

        public async System.Threading.Tasks.Task<System.Int16> GetInt16(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.String>>? headers = default)
        {
            return await this.GetJson<System.Int16>("/GetInt16", System.Array.Empty<Hexarc.Pact.Client.GetMethodParameter>(), headers);
        }

        public async System.Threading.Tasks.Task<System.UInt16> GetUInt16(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.String>>? headers = default)
        {
            return await this.GetJson<System.UInt16>("/GetUInt16", System.Array.Empty<Hexarc.Pact.Client.GetMethodParameter>(), headers);
        }

        public async System.Threading.Tasks.Task<System.Int32> GetInt32(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.String>>? headers = default)
        {
            return await this.GetJson<System.Int32>("/GetInt32", System.Array.Empty<Hexarc.Pact.Client.GetMethodParameter>(), headers);
        }

        public async System.Threading.Tasks.Task<System.UInt32> GetUInt32(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.String>>? headers = default)
        {
            return await this.GetJson<System.UInt32>("/GetUInt32", System.Array.Empty<Hexarc.Pact.Client.GetMethodParameter>(), headers);
        }

        public async System.Threading.Tasks.Task<System.Int64> GetInt64(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.String>>? headers = default)
        {
            return await this.GetJson<System.Int64>("/GetInt64", System.Array.Empty<Hexarc.Pact.Client.GetMethodParameter>(), headers);
        }

        public async System.Threading.Tasks.Task<System.UInt64> GetUInt64(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.String>>? headers = default)
        {
            return await this.GetJson<System.UInt64>("/GetUInt64", System.Array.Empty<Hexarc.Pact.Client.GetMethodParameter>(), headers);
        }

        public async System.Threading.Tasks.Task<System.Single> GetSingle(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.String>>? headers = default)
        {
            return await this.GetJson<System.Single>("/GetSingle", System.Array.Empty<Hexarc.Pact.Client.GetMethodParameter>(), headers);
        }

        public async System.Threading.Tasks.Task<System.Double> GetDouble(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.String>>? headers = default)
        {
            return await this.GetJson<System.Double>("/GetDouble", System.Array.Empty<Hexarc.Pact.Client.GetMethodParameter>(), headers);
        }

        public async System.Threading.Tasks.Task<System.Decimal> GetDecimal(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.String>>? headers = default)
        {
            return await this.GetJson<System.Decimal>("/GetDecimal", System.Array.Empty<Hexarc.Pact.Client.GetMethodParameter>(), headers);
        }

        public async System.Threading.Tasks.Task<System.Guid> GetGuid(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.String>>? headers = default)
        {
            return await this.GetJson<System.Guid>("/GetGuid", System.Array.Empty<Hexarc.Pact.Client.GetMethodParameter>(), headers);
        }

        public async System.Threading.Tasks.Task<System.DateTime> GetDateTime(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.String>>? headers = default)
        {
            return await this.GetJson<System.DateTime>("/GetDateTime", System.Array.Empty<Hexarc.Pact.Client.GetMethodParameter>(), headers);
        }
    }
}

#nullable restore