// <auto-generated>
//   This code was generated by the Hexarc Pact tool. Do not edit.
//   Created: 2021-02-20 19:32:45Z
// </auto-generated>

#nullable enable

namespace Hexarc.Pact.Demo.Client
{
    public sealed partial class DemoClient : Hexarc.Pact.Client.ClientBase
    {
        public Hexarc.Pact.Demo.Api.Controllers.AnimalController Animal { get; }
        public Hexarc.Pact.Demo.Api.Controllers.GeometryController Geometry { get; }
        public Hexarc.Pact.Demo.Api.Controllers.MiscController Misc { get; }

        public DemoClient(System.Net.Http.HttpClient httpClient) : base(httpClient)
        {
            this.Animal = new Hexarc.Pact.Demo.Api.Controllers.AnimalController(this);
            this.Geometry = new Hexarc.Pact.Demo.Api.Controllers.GeometryController(this);
            this.Misc = new Hexarc.Pact.Demo.Api.Controllers.MiscController(this);
        }
    }
}

#nullable restore